// Code generated by lego. DO NOT EDIT.

package {{$.PackageName}}

import (
  "fmt"
  "context"

	"github.com/joshqu1985/lego/encoding/json"
	"github.com/joshqu1985/lego/transport/naming"
	"github.com/joshqu1985/lego/transport/rest"
)
